### ISSUE TITLE
Downloading socrates failed

### ISSUE THREAD

**Issue by ReneFroger** [honza/socrates#21]
Hi there, thanks for sharing this awesome package!

When I tried to download it with the command: 

    pip install -e git://github.com/honza/socrates.git#egg=socrates

After downloading for a while, I get an error

    Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-    7vqchJ/misaka/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-gqi3Yg-record/install-record.txt --single-version-externally-managed --compile --user failed with error code 1 in /tmp/pip-build-7vqchJ/misaka
Storing debug log for failure in /home/renefroger/.pip/pip.log

I use Ubuntu 15.05 by the way. What am I missing yet?

**Comment by honza** [comment]
It looks like it's a known issue with the misaka markdown library — [have a look here](https://github.com/FSX/misaka/issues/47).

**Comment by ReneFroger** [comment]
I got it solved with installing `python-dev` and `libffi-dev`. Thanks for linking it!
