### ISSUE TITLE
When publishing with socrates, the pages could not be found.

### ISSUE THREAD

**Issue by ReneFroger** [honza/socrates#23]
I write a blog page, for example, 2015-11-12-foobar.md

Then I generate a site with `socrates -g` in the current blog directory.

I upload the contents of `deploy` folder to my FTP, and I visit the site then.

I see it's working, everything looks good. And the blogpost `foobar` is listed. When I click on that link, I get the 404-error, he could not find that page.  

URL looks like

    mydomain.nl/2015/11/foobar

When I add `.html` to the end like this. 

    mydomain.nl/2015/11/foobar.html

Then I see the blog contents. Propably Socrates forgot to add .html extension, or the routing is wrong? How could I change that it links to the pages? I found nothing relevant in config.yaml.

**Comment by honza** [comment]
Hm, interesting. I'm using GitHub pages to host my blog and GitHub serves the page correctly when you leave out the `.html` extension.

Are you using apache to serve the site? Maybe an `.htaccess` rule could fix this?

**Comment by ReneFroger** [comment]
I don't use Github. Got it solved, you have probably the following in your `.htaccess` preconfigured:

    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^([^\.]+)$ $1.html [NC,L]
